from langchain_ollama import ChatOllama
from langchain_community.embeddings import OllamaEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
from huggingface_hub import HfFolder

import gradio as gr

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
def get_llm():
    return ChatOllama(model="gemma3:270m")

## Document loader
def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=0,
        # length_function=.....,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

## Vector db
def vector_database(chunks):
    embedding_model = OllamaEmbeddings(model="nomic-embed-text:v1.5") 
    # embedding_model = OllamaEmbeddings(model="embeddinggemma") 
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever

## QA Chain
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=True)
    response = qa.invoke(query)
    print(response['source_documents'], end="\n\n")
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    # allow_flagging=True,
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here..."),
        gr.Checkbox(label="Use Custom Retriever"),
        gr.Radio(choices=["Option 1", "Option 2", "Option 3"], label="Input Query"),
        gr.CheckboxGroup(choices=["Input Query", "q2", "q2"], label="Input Query"),
        gr.Dropdown(label="Input Query"),
    ],
    outputs=gr.Textbox(label="Output"),
    title=gr.Label(num_top_classes=3),
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

if __name__=="__main__":
  # Launch the app
  rag_application.launch(server_name="127.0.0.1", server_port= 5000)